#ifndef _UXR_CLIENT_CONFIG_H_
#define _UXR_CLIENT_CONFIG_H_

#include <sdkconfig.h>

#define UXR_CLIENT_VERSION_MAJOR 1
#define UXR_CLIENT_VERSION_MINOR 0
#define UXR_CLIENT_VERSION_MICRO 1
#define UXR_CLIENT_VERSION_STR "1.0.1"

// Profile configurations
#ifdef CONFIG_PROFILE_CREATE_ENTITIES_REF
#define PROFILE_CREATE_ENTITIES_REF 1
#endif

#ifdef CONFIG_PROFILE_CREATE_ENTITIES_XML
#define PROFILE_CREATE_ENTITIES_XML 1
#endif

#ifdef CONFIG_PROFILE_READ_ACCESS
#define PROFILE_READ_ACCESS         1
#endif

#ifdef CONFIG_PROFILE_WRITE_ACCESS
#define PROFILE_WRITE_ACCESS        1
#endif

#ifdef CONFIG_PROFILE_DISCOVERY
#define PROFILE_DISCOVERY           1
#endif

#ifdef CONFIG_PROFILE_UDP_TRANSPORT
#define PROFILE_UDP_TRANSPORT       1
#endif

#ifdef CONFIG_PROFILE_TCP_TRANSPORT
#define PROFILE_TCP_TRANSPORT       1
#endif

#ifdef CONFIG_PROFILE_SERIAL_TRANSPORT
#define PROFILE_SERIAL_TRANSPORT    1
#endif

// Trick the rest of the source to build as if it was running on Linux
#define PLATFORM_NAME_LINUX 1

#define UXR_CONFIG_MAX_OUTPUT_BEST_EFFORT_STREAMS     CONFIG_MAX_OUTPUT_BEST_EFFORT_STREAMS
#define UXR_CONFIG_MAX_OUTPUT_RELIABLE_STREAMS        CONFIG_MAX_OUTPUT_RELIABLE_STREAMS
#define UXR_CONFIG_MAX_INPUT_BEST_EFFORT_STREAMS      CONFIG_MAX_INPUT_BEST_EFFORT_STREAMS
#define UXR_CONFIG_MAX_INPUT_RELIABLE_STREAMS         CONFIG_MAX_INPUT_RELIABLE_STREAMS

#define UXR_CONFIG_MAX_SESSION_CONNECTION_ATTEMPTS    CONFIG_MAX_SESSION_CONNECTION_ATTEMPTS
#define UXR_CONFIG_MIN_SESSION_CONNECTION_INTERVAL    CONFIG_MIN_SESSION_CONNECTION_INTERVAL
#define UXR_CONFIG_MIN_HEARTBEAT_TIME_INTERVAL        CONFIG_MIN_HEARTBEAT_TIME_INTERVAL

#define UXR_CONFIG_UDP_TRANSPORT_MTU                  CONFIG_UDP_TRANSPORT_MTU
#define UXR_CONFIG_TCP_TRANSPORT_MTU                  CONFIG_TCP_TRANSPORT_MTU
#define UXR_CONFIG_SERIAL_TRANSPORT_MTU               CONFIG_SERIAL_TRANSPORT_MTU

#ifdef CONFIG_VERBOSE_MESSAGE
#define UXR_MESSAGE_LOGS             1
#endif

#ifdef CONFIG_VERBOSE_SERIALIZATION
#define UXR_MESSAGE_SERIALIZATION    1
#endif

#endif // _UXR_CLIENT_CONFIG_H_
